[package]
name = "neural_network"
version = "0.1.0"
authors = ["Sugi <developer.sugiono@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"